-- Database Migration: Fix menu table primary key and foreign key
-- 1. Make item_id an identity column (auto-increment)
-- 2. Add foreign key constraint on rest_id -> sellers(seller_id)

BEGIN;

-- 1. Ensure item_id is integer and auto-increments
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'menu' AND column_name = 'item_id' AND identity_generation IS NOT NULL
  ) THEN
    -- Drop default sequence if exists
    ALTER TABLE menu ALTER COLUMN item_id DROP DEFAULT;
    -- Make item_id bigint to allow identity change then convert back to int
    ALTER TABLE menu ALTER COLUMN item_id TYPE INTEGER USING item_id::INTEGER;
    -- Add identity generation
    ALTER TABLE menu ALTER COLUMN item_id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- 2. Add foreign key constraint for rest_id if not exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_type = 'FOREIGN KEY' AND table_name = 'menu' AND constraint_name = 'fk_menu_rest'
  ) THEN
    ALTER TABLE menu 
    ADD CONSTRAINT fk_menu_rest FOREIGN KEY (rest_id) REFERENCES sellers(seller_id) ON DELETE CASCADE;
  END IF;
END $$;

COMMIT; 